# Generated by Django 5.2.5 on 2026-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_rename_teacher_course_teacher_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='timetable',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='timetable',
            name='days',
            field=models.ManyToManyField(related_name='timetables', to='academics.day'),
        ),
    ]
