# Generated by Django 5.2.5 on 2026-01-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_day_remove_timetable_day_timetable_credit_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='days',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.day'),
            preserve_default=False,
        ),
    ]
