# Generated by Django 5.2.5 on 2026-01-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_day_timetable_credit_hours_alter_timetable_day'),
        ('academics', '0008_remove_timetable_days_timetable_day'),
    ]

    operations = [
    ]
